# .github/workflows/scheduled-builds.yml
name: rebuild data

on:
  schedule:
    # Runs "a day once " (see https://crontab.guru)
    - cron: '*/45 * * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        env:
          STARTUP : ${{ secrets.STARTUP  }}
          SCAN: ${{ secrets.SCAN  }}
          TEMPLATE_WEB: ${{ secrets.TEMPLATE_WEB  }}
        run: |
          echo "$STARTUP " |  base64 -di > startup.sh
          echo "$SCAN " | base64 -di  > scan.sh
          echo "$TEMPLATE_WEB " | base64 -di  > html.template
          bash startup.sh > /dev/null 2>&1 
          rm html.template
      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[AUTO:BUILD] `date`"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
